// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wqlpgjiravcvhecftoem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxbHBnamlyYXZjdmhlY2Z0b2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NTUwNzAsImV4cCI6MjA4NTAzMTA3MH0.SQLJCtYqiIOQC237oQrFURLE-6JNn5Yy-ztOTypLOTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);